var
	aTopicList: THndTopicsInfoArray;
	nCurTopic: integer;
	sModuleName: string;

begin
	HndGeneratorInfo.CurrentFile := ExtractFileName(HndGeneratorInfo.OutputFile);
	sModuleName := ChangeFileExt(ExtractFileName(HndGeneratorInfo.OutputFile), '');
	aTopicList := HndTopics.GetTopicList(False);
	
	printfln('# Project: %s', [HndProjects.GetProjectTitle()]);
	println ('# Generated by HelpNDoc - http://www.helpndoc.com');
	println ('');
	for nCurTopic := 0 to length(aTopicList) - 1 do
	begin
		printfln('public const HELP_%s as integer = %d', [aTopicList[nCurTopic].HelpId, aTopicList[nCurTopic].HelpContext]);
	end;
	
end.