var
	aTopicList: THndTopicsInfoArray;
	nCurTopic: integer;
	sModuleName: string;

begin
	HndGeneratorInfo.CurrentFile := ExtractFileName(HndGeneratorInfo.OutputFile);
	sModuleName := ChangeFileExt(ExtractFileName(HndGeneratorInfo.OutputFile), '');
	aTopicList := HndTopics.GetTopicList(False);
	
	printfln('# Project: %s', [HndProjects.GetProjectTitle()]);
	println ('# Generated by HelpNDoc - http://www.helpndoc.com');
	println ('');
	printfln('Public Enum eHelp_%s', [sModuleName]);
	for nCurTopic := 0 to length(aTopicList) - 1 do
	begin
		printfln('  HELP_%s = %d', [aTopicList[nCurTopic].HelpId, aTopicList[nCurTopic].HelpContext]);
	end;
	println ('End Enum');
	
end.